### Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ. 

In [32]:
import numpy as np
import pandas as pd
from scipy import stats

### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy. Полученные значения должны быть равны. Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas. 

In [33]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [34]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [35]:
# Вычислим ковариацию по формуле:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [36]:
# Найдем ковариацию с помощью функции cov из numpy:
np.cov(zp, ks, ddof=0) [0, 1]  

9157.840000000002

Вывод: полученные значения ковариаций равны.

In [37]:
# Найдем коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков:
corrcoef = np.cov(zp, ks, ddof=0) [0, 1] / (np.std(zp, ddof=0) * np.std(ks, ddof=0))
corrcoef

0.8874900920739163

In [38]:
# Найдем коэффициент корреляции Пирсона с помощью функции из библиотеки numpy:
np.corrcoef(zp, ks)[0, 1]

0.8874900920739163

In [39]:
# Найдем коэффициент корреляции Пирсона с помощью функции из библиотеки pandas:
df = pd.DataFrame({'zp': zp, 'ks': ks}, columns=['zp', 'ks'])
r_pd = df.corr().values[0, 1]
r_pd

0.8874900920739168

### 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [40]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [41]:
mu = np.mean(iq) # среднее по выборке
mu

118.1

In [42]:
std = np.std(iq, ddof=1) # несмещенное стандартное отклонение
std

10.54566788359614

In [43]:
p = 0.95
alpha = 1 - p
n = 10
# найдем критерии Стьюдента:
t1 = stats.t.ppf(alpha / 2, df = n - 1)
t2 = stats.t.ppf(1 - alpha / 2, df = n - 1)
t1, t2

(-2.2621571627409915, 2.2621571627409915)

In [44]:
a1 = mu + t1 * std / np.sqrt(n) # левая граница
a2 = mu + t2 * std / np.sqrt(n) # правая граница

print(f'Ответ: доверительный интервал ({a1}; {a2})')

Ответ: доверительный интервал (110.55608365158724; 125.64391634841274)


### 3. Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95. 

In [45]:
std = np.sqrt(25)
n = 27
mu = 174.2
p = 0.95
alpha = 1 - p
# считаем z-критерии:
z1 = stats.norm.ppf(alpha / 2)
z2 = stats.norm.ppf(1 - alpha / 2)
z1, z2

(-1.959963984540054, 1.959963984540054)

In [46]:
a1 = mu + z1 * std / np.sqrt(n) # левая граница
a2 = mu + z2 * std / np.sqrt(n) # правая граница

print(f'Ответ: доверительный интервал ({a1}; {a2})')

Ответ: доверительный интервал (172.3140237765397; 176.08597622346028)
